### ISSUE TITLE
OpenGL plugins don't render anything when I compile them

### ISSUE THREAD

**Issue by yaw-man** [DISTRHO/DPF#386] opened 2022-10-19 21:37 UTC
Compiling on Windows, using Visual Studio 2022 Community's compiler for amd64.

Picture of Nekobi VST2, hosted in OpenMPT:
![image](https://user-images.githubusercontent.com/85530488/196805014-cb31ed4b-f3fd-44b5-af4f-cacb96aeca7a.png)

Picture confirming that the plugin actually calls OpenGL:
![image](https://user-images.githubusercontent.com/85530488/196807304-91e55e08-b351-4d74-96c8-e000c148d08a.png)

Repo with the CMakeLists files I used to build this: https://github.com/yaw-man/Nekobi

**Comment by falkTX** [comment] 2022-10-19 22:10
How does your image confirms it?
Is that a debug flag or something..?

**Comment by yaw-man** [comment] 2022-10-24 01:58
My apologies - reading it back, the image is not at all self-explanatory!
I attached a debugger to the plugin, set a breakpoint at DistrhoUINekobi's constructor, then stepped through until I saw an OpenGL call.
If that doesn't actually confirm that the plugin is using the right backend, let me know :)

**Comment by falkTX** [comment] 2022-10-30 19:08
I am wondering if this due to the version of DPF you are using.
I just updated the main branch to get all the latest features and fixes, so update your DPF submodule and try again.
Latest commit is "Fix typo leading some VST3 groups having 0 ports".

Let me know if/how that works for you.

**Comment by falkTX** [comment] 2022-10-30 22:03
Actually I can reproduce this now. Something broke for opengl-based Windows with DPF a while ago and went unnoticed.
The commit a941917f15be21e6bdce6793addec225537cccc5 doesn't have the issue. So it is something after that one.

**Comment by falkTX** [comment] 2022-10-30 22:06
Found it, commit f26b8147d309f8b3cdcaa6b3e6d8dac773658009 is the regression.
This was supposed to fix another issue, but resulted in bad things for us...

**Comment by falkTX** [comment] 2022-10-31 00:53
Fixed in 241845f387f03473e84254f7bfb73bd09460417a

**Closed by falkTX** 2022-10-31 00:53 UTC
