### ISSUE TITLE
setLatency behaviour seems not to work correctly on LV2, not at all on VST

### ISSUE THREAD

**Issue by TheOnlyJoey** [DISTRHO/DPF#243] opened 2020-11-08 18:55 UTC
Behavior on the lv2 latency example plugin seems to be incorrect. Even though it seems to be synced/corrected, it waits the amount of latency before it starts moving the playhead (so with 5 seconds, it waits 5 seconds before it starts doing anything)
and when bypassing during playback, it jumps the playhead with the amount of seconds delay in the plugin.
Also when jumping the playhead it still plays part of the old buffer before stopping, filling up and then playing from where it started.

The VST plugin just does not do anything with the latency set, I expect something not behaving correctly in the implementation.

Tested with Ardour 6.3 and Reaper 6.15 on Linux.

**Comment by falkTX** [comment] 2022-10-12 01:28
The missing VST2 support was fixed in ca8f83de76bad741286620b5060fedd9ad598a0e
I simply forgot to set the latency value there, verified to work in at least one host.

Now regarding the usefulness of the plugin... it is kinda intentionally barebones, the purpose is to show how to use the latency API (which is a single call).
We could make it more fancy, restarting the fill of audio when transport is relocated or with fancy bypass or other features, but honestly that easily becomes its own plugin which I consider out of scope.
The DPF examples serve to showcase the API first, and help in testing and development.
Any actual user-level usefulness is purely coincidental.

For that reason I consider the issue fixed, in the sense that it works as intended (ie, API demo purposes) and the VST2 issue is resolved.

**Closed by falkTX** 2022-10-12 01:28 UTC
Labels: bug
